// <auto-generated />
using System;
using FighterTrainer.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FighterTrainer.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116151337_CreatePresenca")]
    partial class CreatePresenca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Atleta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Agilidade")
                        .HasColumnType("integer")
                        .HasColumnName("agilidade");

                    b.Property<int>("Altura")
                        .HasColumnType("integer")
                        .HasColumnName("altura");

                    b.Property<string>("Apelido")
                        .HasColumnType("text")
                        .HasColumnName("apelido");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacadastro");

                    b.Property<int>("Defesa")
                        .HasColumnType("integer")
                        .HasColumnName("defesa");

                    b.Property<int>("FocoMental")
                        .HasColumnType("integer")
                        .HasColumnName("focomental");

                    b.Property<int>("LutaEmPe")
                        .HasColumnType("integer")
                        .HasColumnName("lutaempe");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.Property<int>("Resistencia")
                        .HasColumnType("integer")
                        .HasColumnName("resistencia");

                    b.Property<int>("Solo")
                        .HasColumnType("integer")
                        .HasColumnName("solo");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuarioid");

                    b.Property<int>("Wrestling")
                        .HasColumnType("integer")
                        .HasColumnName("wrestling");

                    b.HasKey("Id");

                    b.ToTable("atletas", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Cidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("cidade", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Federacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("federacao", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.FichaTreino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("bigint")
                        .HasColumnName("atletaid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<long>("TurmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("turmaid");

                    b.Property<long>("UsuarioModalidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuariomodalidadeid");

                    b.HasKey("Id");

                    b.HasIndex("AtletaId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("UsuarioModalidadeId");

                    b.ToTable("fichastreino", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Graduacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("FederacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("federacaoid");

                    b.Property<int?>("Grau")
                        .HasColumnType("integer")
                        .HasColumnName("grau");

                    b.Property<long>("ModalidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("modalidadeid");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.HasKey("Id");

                    b.HasIndex("FederacaoId");

                    b.ToTable("graduacao", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Modalidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.ToTable("modalidade", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Presenca", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AtletaId")
                        .HasColumnType("bigint")
                        .HasColumnName("atletaid");

                    b.Property<DateTime>("DataHoraCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datahoracadastro");

                    b.Property<long>("TurmaId")
                        .HasColumnType("bigint")
                        .HasColumnName("turmaid");

                    b.HasKey("Id");

                    b.HasIndex("TurmaId");

                    b.HasIndex("AtletaId", "TurmaId")
                        .IsUnique();

                    b.ToTable("presenca", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Treinador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacadastro");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("treinadores", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Turma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<TimeOnly>("HoraFimAula")
                        .HasColumnType("time")
                        .HasColumnName("horafimaula");

                    b.Property<TimeOnly>("HoraInicioAula")
                        .HasColumnType("time")
                        .HasColumnName("horainicioaula");

                    b.Property<int>("LimiteAlunos")
                        .HasColumnType("integer")
                        .HasColumnName("limitealunos");

                    b.Property<long>("ModalidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("modalidadeid");

                    b.Property<long>("TreinadorResponsavelId")
                        .HasColumnType("bigint")
                        .HasColumnName("treinadorresponsavelid");

                    b.Property<long>("UnidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("unidadeid");

                    b.HasKey("Id");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("TreinadorResponsavelId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("turma", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Unidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<long>("CidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("cidadeid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacriacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("unidade", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.UsuarioModalidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datainicio");

                    b.Property<long>("GraduacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("graduacaoid");

                    b.Property<long>("ModalidadeId")
                        .HasColumnType("bigint")
                        .HasColumnName("modalidadeid");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuarioid");

                    b.HasKey("Id");

                    b.HasIndex("GraduacaoId");

                    b.HasIndex("ModalidadeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("usuariomodalidade", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Usuarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datacadastro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senhahash");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipousuario");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.FichaTreino", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.UsuarioModalidade", "UsuarioModalidade")
                        .WithMany()
                        .HasForeignKey("UsuarioModalidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Turma");

                    b.Navigation("UsuarioModalidade");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Graduacao", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Federacao", "Federacao")
                        .WithMany()
                        .HasForeignKey("FederacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Federacao");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Presenca", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("AtletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Atleta");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Treinador", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Turma", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Modalidade", "Modalidade")
                        .WithMany()
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.Treinador", "Treinador")
                        .WithMany()
                        .HasForeignKey("TreinadorResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modalidade");

                    b.Navigation("Treinador");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Unidade", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.UsuarioModalidade", b =>
                {
                    b.HasOne("FighterTrainer.Domain.Entities.Graduacao", "Graduacao")
                        .WithMany()
                        .HasForeignKey("GraduacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.Modalidade", "Modalidade")
                        .WithMany()
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FighterTrainer.Domain.Entities.Usuarios", "Usuario")
                        .WithMany("UsuarioModalidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Graduacao");

                    b.Navigation("Modalidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FighterTrainer.Domain.Entities.Usuarios", b =>
                {
                    b.Navigation("UsuarioModalidades");
                });
#pragma warning restore 612, 618
        }
    }
}
